// Mocks generated by Mockito 5.4.4 from annotations
// in okumanya/test/features/books/domain/usecases/get_books_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:okumanya/core/error/failures.dart' as _i5;
import 'package:okumanya/features/books/domain/entities/book.dart' as _i6;
import 'package:okumanya/features/books/domain/repositories/books_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BooksRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBooksRepository extends _i1.Mock implements _i3.BooksRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>> getAllBooks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllBooks,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #getAllBooks,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #getAllBooks,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>> getBooksByCategory(
          String? category) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBooksByCategory,
          [category],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #getBooksByCategory,
            [category],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #getBooksByCategory,
            [category],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>> searchBooks(
          String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchBooks,
          [query],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #searchBooks,
            [query],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #searchBooks,
            [query],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Book>> getBookById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookById,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Book>>.value(
            _FakeEither_0<_i5.Failure, _i6.Book>(
          this,
          Invocation.method(
            #getBookById,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Book>>.value(
                _FakeEither_0<_i5.Failure, _i6.Book>(
          this,
          Invocation.method(
            #getBookById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Book>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Book>> updateBookProgress(
    String? bookId,
    double? progress,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookProgress,
          [
            bookId,
            progress,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Book>>.value(
            _FakeEither_0<_i5.Failure, _i6.Book>(
          this,
          Invocation.method(
            #updateBookProgress,
            [
              bookId,
              progress,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Book>>.value(
                _FakeEither_0<_i5.Failure, _i6.Book>(
          this,
          Invocation.method(
            #updateBookProgress,
            [
              bookId,
              progress,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Book>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Book>> toggleBookFavorite(
          String? bookId) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleBookFavorite,
          [bookId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Book>>.value(
            _FakeEither_0<_i5.Failure, _i6.Book>(
          this,
          Invocation.method(
            #toggleBookFavorite,
            [bookId],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, _i6.Book>>.value(
                _FakeEither_0<_i5.Failure, _i6.Book>(
          this,
          Invocation.method(
            #toggleBookFavorite,
            [bookId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.Book>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>> getFavoriteBooks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getFavoriteBooks,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #getFavoriteBooks,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #getFavoriteBooks,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>> getRecentBooks() =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentBooks,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #getRecentBooks,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #getRecentBooks,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<String>>> getCategories() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
            _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #getCategories,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<String>>>.value(
                _FakeEither_0<_i5.Failure, List<String>>(
          this,
          Invocation.method(
            #getCategories,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<String>>>);
}
