// Mocks generated by Mockito 5.4.4 from annotations
// in okumanya/test/features/books/presentation/bloc/books_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:okumanya/core/error/failures.dart' as _i5;
import 'package:okumanya/features/books/domain/entities/book.dart' as _i6;
import 'package:okumanya/features/books/domain/usecases/get_books.dart' as _i3;
import 'package:okumanya/features/books/domain/usecases/get_books_by_category.dart'
    as _i8;
import 'package:okumanya/features/books/domain/usecases/search_books.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetBooks].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBooks extends _i1.Mock implements _i3.GetBooks {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>);
}

/// A class which mocks [SearchBooks].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchBooks extends _i1.Mock implements _i7.SearchBooks {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>> call(
          _i7.SearchBooksParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>);
}

/// A class which mocks [GetBooksByCategory].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBooksByCategory extends _i1.Mock
    implements _i8.GetBooksByCategory {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>> call(
          _i8.GetBooksByCategoryParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
            _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.Book>>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Book>>>);
}
